// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF1HBroWYMhMqQXw71ivs-O_7RT9b34hM',
    appId: '1:830864962380:web:0e3fd601b9a462818255e9',
    messagingSenderId: '830864962380',
    projectId: 'events-uganda',
    authDomain: 'events-uganda.firebaseapp.com',
    storageBucket: 'events-uganda.firebasestorage.app',
    measurementId: 'G-EGRLQQ7GNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpBekZrexbvQan6Uo6Sl4DZJCBDF04-7I',
    appId: '1:830864962380:android:7842c491b29dd5988255e9',
    messagingSenderId: '830864962380',
    projectId: 'events-uganda',
    storageBucket: 'events-uganda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClaDDH46bLQc_chYJ91y2PL3TLrTuag1s',
    appId: '1:830864962380:ios:81c1592aefd3b38a8255e9',
    messagingSenderId: '830864962380',
    projectId: 'events-uganda',
    storageBucket: 'events-uganda.firebasestorage.app',
    androidClientId: '830864962380-64roui1d04g7bhfq8jtq0l7es3adln63.apps.googleusercontent.com',
    iosClientId: '830864962380-lrsb10ufdoj3j376h6q7qd5640djtjsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventsUganda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClaDDH46bLQc_chYJ91y2PL3TLrTuag1s',
    appId: '1:830864962380:ios:81c1592aefd3b38a8255e9',
    messagingSenderId: '830864962380',
    projectId: 'events-uganda',
    storageBucket: 'events-uganda.firebasestorage.app',
    androidClientId: '830864962380-64roui1d04g7bhfq8jtq0l7es3adln63.apps.googleusercontent.com',
    iosClientId: '830864962380-lrsb10ufdoj3j376h6q7qd5640djtjsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventsUganda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF1HBroWYMhMqQXw71ivs-O_7RT9b34hM',
    appId: '1:830864962380:web:64e549f3db9bc0bd8255e9',
    messagingSenderId: '830864962380',
    projectId: 'events-uganda',
    authDomain: 'events-uganda.firebaseapp.com',
    storageBucket: 'events-uganda.firebasestorage.app',
    measurementId: 'G-50Z0ZN0XJC',
  );
}
